-- Health Check: PostgreSQL
-- Generated by dwm
SELECT
    version() AS pg_version,
    current_database() AS database,
    current_user AS connected_user,
    now() AS server_time,
    pg_size_pretty(pg_database_size(current_database())) AS db_size;
